apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Chart.Name}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
type: opaque
stringData:
  LINE_CHANNEL_TOKEN: {{ .Values.secretMap.LINE_CHANNEL_TOKEN | quote }}
  MONGODB_URL:  {{ .Values.secretMap.MONGODB_URL | quote }}
  REDIS_URL: {{ .Values.secretMap.REDIS_URL | quote }}
  CLIENT_URL: {{ .Values.secretMap.CLIENT_URL | quote }}
  KAFKA_URL: {{ .Values.secretMap.KAFKA_URL | quote }}
  


